### ISSUE TITLE
openload.co lỗi

### ISSUE THREAD

**Issue by teamhday** [nmtrung/FMSF-3x#1]
http://tuoi69.com/scandal-clipsex-mua-dam-em-gai-tuoi-vi-thanh-nien-dang-gay-chu-y
https://openload.co/f/0zOIyGRFNLM/
The publisher of this file doesnt allow adblock, please disable and reload

**Comment by nmtrung** [comment]
@teamhday : Đã fix openload.co bên FMSF-2. Bên đây thì chặn site đầu tiên tuoi69.com
Thank thím đã report
