### ISSUE TITLE
Javlibrary

### ISSUE THREAD

**Issue by usernam1911** [nmtrung/FMSF-3x#2]
Bác chặn giúp trang này và mấy trang up ảnh trong phần comment bên dưới
http://www.javlibrary.com/en/?v=javlikjcqi
http://imgspice.com/ss45s4k5tya5/0603hnd411c.jpg.html
http://imagetwist.com/089kaiwl5spv/0603hnd411c.jpg
http://www.imgbabes.com/nwvf493zzphj/HND-411_s.jpg.html

**Comment by nmtrung** [comment]
@usernam1911 : trang đầu tiên bị gì bạn?

**Comment by usernam1911** [comment]
Trang đó có popup, bác vào vài lần sẽ thấy

**Comment by motbannamgiautrym** [comment]
có trang nào hay hay có mấy e xinh tươi của vịt ko các bác, xem jav chán quá 😆

**Comment by nmtrung** [comment]
@motbannamgiautrym : chuyển sang vav đi thím :sexy:

**Comment by motbannamgiautrym** [comment]
có suggest nào ko bác chủ 😍

**Comment by nmtrung** [comment]
@motbannamgiautrym : tuoi69 ấy

**Comment by nmtrung** [comment]
@usernam1911 : Đã fix, mời update
